#Requires -Version 7.0
<#
.SYNOPSIS
    Start one named Business Central instance against the shared SQL Server and
    the shared Traefik proxy.

.DESCRIPTION
    Each instance is its own compose project (bc-<name>) on the shared bcnet
    network, so instances start and stop independently and none of them owns
    the database server or the proxy.

    The instance's service definition is generated by running
    "docker compose config" over the BcOnLinux repo and taking its bc service,
    rather than by copying it. That way the instance tracks upstream changes.
    depends_on is dropped, because the shared SQL Server is not part of this
    project and the BC entrypoint waits for SQL on its own anyway.

    Settings live in a manifest at <platform>/instances/<name>.env. If it does
    not exist yet, pass the values once and they are written there; later runs
    need only the name.

.EXAMPLE
    ./bc-up.ps1 bc28 -BcRepo ~/BcOnLinux/repo
    ./bc-up.ps1 bc28
    ./bc-up.ps1 bc28 -Json
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory, Position = 0)]
    [ValidatePattern('^[a-z0-9][a-z0-9-]*$')]
    [string]$Name,

    # Path to the BcOnLinux checkout. Required the first time an instance is created.
    [string]$BcRepo,
    # host:port the browser uses. Defaults to whatever traefik-up was given.
    [string]$PublicHost,
    [string]$SaPassword,
    [string]$AadAppId,
    [string]$AadTenantId,
    [string]$AadUserUpn,
    [string]$HttpsPfx = '/certs/bc.pfx',
    [string]$HttpsPfxPassword,
    # Add a second web client on NavUserPassword at /<name>dev, for agents
    # that have no Entra account. The main one keeps whatever sign-in it had.
    [switch]$AgentWebClient,
    [switch]$Json
)

$ErrorActionPreference = 'Stop'

$platformHome = if ($env:BC_PLATFORM_HOME) { $env:BC_PLATFORM_HOME } else { Join-Path $HOME '.bc-platform' }
$network      = 'bcnet'
$project      = "bc-$Name"
$instanceDir  = Join-Path $platformHome "instances/$Name"
$manifest     = Join-Path $platformHome "instances/$Name.env"

New-Item -ItemType Directory -Force -Path $instanceDir | Out-Null

function Read-EnvFile([string]$path) {
    $map = [ordered]@{}
    if (Test-Path $path) {
        foreach ($line in Get-Content $path) {
            if ($line -match '^\s*#' -or $line -notmatch '=') { continue }
            $k, $v = $line -split '=', 2
            $map[$k.Trim()] = $v
        }
    }
    $map
}

$cfg = Read-EnvFile $manifest

# --- resolve settings: explicit parameter wins, then manifest, then platform ---
$sqlEnv     = Read-EnvFile (Join-Path $platformHome 'mssql/.env')
$traefikEnv = Read-EnvFile (Join-Path $platformHome 'traefik/.env')

if ($BcRepo)           { $cfg['BC_ON_LINUX_DIR'] = (Resolve-Path $BcRepo).Path }
if ($PublicHost)       { $cfg['PUBLIC_HOST'] = $PublicHost }
if ($SaPassword)       { $cfg['SA_PASSWORD'] = $SaPassword }
if ($AadAppId)         { $cfg['BC_AAD_APP_ID'] = $AadAppId }
if ($AadTenantId)      { $cfg['BC_AAD_TENANT_ID'] = $AadTenantId }
if ($AadUserUpn)       { $cfg['BC_AAD_USER_UPN'] = $AadUserUpn }
if ($HttpsPfxPassword) { $cfg['BC_WEBCLIENT_HTTPS_PFX_PASSWORD'] = $HttpsPfxPassword }

if (-not $cfg['PUBLIC_HOST'] -and $traefikEnv['PUBLIC_HOST']) { $cfg['PUBLIC_HOST'] = $traefikEnv['PUBLIC_HOST'] }
if (-not $cfg['SA_PASSWORD'] -and $sqlEnv['SA_PASSWORD'])     { $cfg['SA_PASSWORD'] = $sqlEnv['SA_PASSWORD'] }

$missing = @()
if (-not $cfg['BC_ON_LINUX_DIR']) { $missing += '-BcRepo (path to the BcOnLinux checkout)' }
if (-not $cfg['PUBLIC_HOST'])     { $missing += '-PublicHost (or run the traefik-up skill first)' }
if (-not $cfg['SA_PASSWORD'])     { $missing += '-SaPassword (or run the mssql-up skill first)' }
if ($missing.Count) {
    throw "Instance '$Name' is not configured yet. Missing:`n  " + ($missing -join "`n  ")
}
if (-not (Test-Path (Join-Path $cfg['BC_ON_LINUX_DIR'] 'docker-compose.yml'))) {
    throw "No docker-compose.yml in $($cfg['BC_ON_LINUX_DIR'])."
}

# --- allocate a contiguous host port block, once, and remember it ---
if (-not $cfg['BC_PORT_BASE']) {
    $claimed = @(Get-ChildItem -Path (Join-Path $platformHome 'instances') -Filter '*.env' -ErrorAction SilentlyContinue |
        ForEach-Object { (Read-EnvFile $_.FullName)['BC_PORT_BASE'] } | Where-Object { $_ })
    $base = 7000
    while ("$base" -in $claimed) { $base += 100 }
    $cfg['BC_PORT_BASE'] = "$base"
}
$base = [int]$cfg['BC_PORT_BASE']

$cfg['BC_MGMT_PORT']           = "$($base + 45)"
$cfg['BC_ODATA_PORT']          = "$($base + 48)"
$cfg['BC_DEV_PORT']            = "$($base + 49)"
$cfg['BC_API_PORT']            = "$($base + 52)"
$cfg['BC_CLIENT_PORT']         = "$($base + 85)"
$cfg['BC_WEBCLIENT_HOST_PORT'] = "$($base + 80)"

# --- fixed instance settings ---
$cfg['SQL_SERVER']                   = 'bc-mssql'
$cfg['BC_WEBCLIENT']                 = '1'
$cfg['BC_WEBCLIENT_PATHBASE']        = "/$Name"
$cfg['BC_WEBCLIENT_PUBLIC_URL']      = "https://$($cfg['PUBLIC_HOST'])/$Name/"
$cfg['BC_WEBCLIENT_PUBLIC_HOST']     = $cfg['PUBLIC_HOST']
$cfg['BC_WEBCLIENT_HTTPS_PFX']       = $HttpsPfx
$cfg['BC_WEBCLIENT_FORWARDED_HEADERS'] = '0'
if ($AgentWebClient) {
    $cfg['BC_WEBCLIENT_AGENT']          = '1'
    $cfg['BC_WEBCLIENT_AGENT_PORT']     = '8081'
    $cfg['BC_WEBCLIENT_AGENT_PATHBASE'] = "/${Name}dev"
}
# Placeholder credentials for Basic auth against the OData, API and dev
# endpoints. The service tier runs NavUserPassword, so these work at every
# web-services surface; the web client signs in through Entra separately.
# Set them in the instance manifest to override; a value already there
# wins over this default.
if (-not $cfg['BC_SERVER_USERNAME']) { $cfg['BC_SERVER_USERNAME'] = 'user' }
if (-not $cfg['BC_SERVER_PASSWORD']) { $cfg['BC_SERVER_PASSWORD'] = 'Password1.' }

$cfg.GetEnumerator() | ForEach-Object { "$($_.Key)=$($_.Value)" } | Set-Content -Path $manifest

# --- generate the instance compose from the upstream bc service ---
# --env-file replaces the repo's own .env rather than adding to it, so defaults
# the repo sets there would silently vanish. Merge instead: repo values first,
# manifest second, last one wins.
$mergedEnv = Join-Path $instanceDir 'merged.env'
$repoEnv   = Join-Path $cfg['BC_ON_LINUX_DIR'] '.env'
$mergedLines = @()
if (Test-Path $repoEnv) { $mergedLines += Get-Content $repoEnv }
$mergedLines += ($cfg.GetEnumerator() | ForEach-Object { "$($_.Key)=$($_.Value)" })
$mergedLines | Set-Content -Path $mergedEnv

$raw = docker compose --project-directory $cfg['BC_ON_LINUX_DIR'] --env-file $mergedEnv config --format json 2>$null
if (-not $raw) { throw "docker compose config failed for $($cfg['BC_ON_LINUX_DIR'])." }
$upstream = $raw | ConvertFrom-Json -AsHashtable
$svc = $upstream.services.bc
if (-not $svc) { throw "No 'bc' service in $($cfg['BC_ON_LINUX_DIR'])/docker-compose.yml." }

# The shared SQL Server is not in this project, and the entrypoint waits for
# SQL itself, so the dependency is both unsatisfiable and unnecessary here.
$svc.Remove('depends_on')
$svc.Remove('profiles')
$svc['container_name'] = "bc-$Name"
$svc['restart'] = 'unless-stopped'
$svc['networks'] = @{ $network = $null; default = $null }
# Run the repo's scripts rather than the copy baked into the image, so editing
# entrypoint.sh or start-webclient.sh takes effect on the next container start
# instead of on the next `docker compose build`.
$svc['volumes'] += @{
    type      = 'bind'
    source    = (Join-Path $cfg['BC_ON_LINUX_DIR'] 'scripts')
    target    = '/bc/scripts'
    read_only = $true
    bind      = @{}
}

# A path base served by UsePathBase has no trailing-slash redirect of its own,
# the way an IIS virtual directory does. Without one the browser can sit on
# /<name> and the web client's client-side navigation concatenates to
# /<name>SignIn. The public host is written out rather than captured from the
# request, because a devtunnel relay rewrites Host to localhost before the
# proxy sees it.
$slashRegex = '^[a-z]+://[^/]+/{0}(\?.*)?$' -f $Name
$slashTo    = 'https://{0}/{1}/${{1}}' -f $cfg['PUBLIC_HOST'], $Name

$svc['labels'] = @{
    'traefik.enable'                                                    = 'true'
    "traefik.http.routers.$Name.rule"                                   = "PathPrefix(``/$Name``)"
    "traefik.http.routers.$Name.entrypoints"                            = 'web'
    "traefik.http.routers.$Name.service"                                = $Name
    "traefik.http.routers.$Name.middlewares"                            = 'publichost@file'
    "traefik.http.services.$Name.loadbalancer.server.port"              = '8080'
    "traefik.http.services.$Name.loadbalancer.server.scheme"            = 'https'
    "traefik.http.services.$Name.loadbalancer.serverstransport"         = 'bc-transport@file'
    "traefik.http.services.$Name.loadbalancer.passhostheader"           = 'true'
    "traefik.http.routers.$Name.priority"                               = '100'
    "traefik.http.middlewares.$Name-slash.redirectregex.regex"          = $slashRegex
    "traefik.http.middlewares.$Name-slash.redirectregex.replacement"    = $slashTo
    "traefik.http.routers.$Name-slash.rule"                             = "Path(``/$Name``)"
    "traefik.http.routers.$Name-slash.priority"                         = '200'
    "traefik.http.routers.$Name-slash.entrypoints"                      = 'web'
    "traefik.http.routers.$Name-slash.middlewares"                      = "$Name-slash"
    "traefik.http.routers.$Name-slash.service"                          = $Name
    'bc.instance'                                                       = $Name
}

# The agent web client is a second front end on the same container, so it is a
# second router and service rather than a second instance. Its prefix is longer
# than the main one's and would win on rule length alone; the priorities are
# explicit so that stays true if either rule changes.
if ($AgentWebClient) {
    $agent           = "${Name}dev"
    $agentSlashRegex = '^[a-z]+://[^/]+/{0}(\?.*)?$' -f $agent
    $agentSlashTo    = 'https://{0}/{1}/${{1}}' -f $cfg['PUBLIC_HOST'], $agent
    $svc['labels'] += @{
        "traefik.http.routers.$agent.rule"                            = "PathPrefix(``/$agent``)"
        "traefik.http.routers.$agent.priority"                        = '150'
        "traefik.http.routers.$agent.entrypoints"                     = 'web'
        "traefik.http.routers.$agent.service"                         = $agent
        "traefik.http.routers.$agent.middlewares"                     = 'publichost@file'
        "traefik.http.services.$agent.loadbalancer.server.port"       = $cfg['BC_WEBCLIENT_AGENT_PORT']
        "traefik.http.services.$agent.loadbalancer.server.scheme"     = 'https'
        "traefik.http.services.$agent.loadbalancer.serverstransport"  = 'bc-transport@file'
        "traefik.http.services.$agent.loadbalancer.passhostheader"    = 'true'
        "traefik.http.middlewares.$agent-slash.redirectregex.regex"       = $agentSlashRegex
        "traefik.http.middlewares.$agent-slash.redirectregex.replacement" = $agentSlashTo
        "traefik.http.routers.$agent-slash.rule"                      = "Path(``/$agent``)"
        "traefik.http.routers.$agent-slash.priority"                  = '250'
        "traefik.http.routers.$agent-slash.entrypoints"               = 'web'
        "traefik.http.routers.$agent-slash.middlewares"               = "$agent-slash"
        "traefik.http.routers.$agent-slash.service"                   = $agent
    }
}

# Named volumes: the artifact cache is shared across instances because it is a
# read-only download cache and re-fetching it per instance costs gigabytes. The
# service and assembly-cache volumes stay project-scoped so instances stay
# independent.
$volumes = @{ 'bc-artifacts' = @{ external = $true; name = 'bc-artifacts' } }
foreach ($v in @($svc.volumes | Where-Object { $_.type -eq 'volume' })) {
    if ($v.source -ne 'bc-artifacts') { $volumes[$v.source] = @{} }
}

$doc = @{
    name     = $project
    services = @{ bc = $svc }
    volumes  = $volumes
    networks = @{ $network = @{ external = $true }; default = @{} }
}

# JSON is valid YAML, so Compose reads this file directly and we avoid
# hand-rolling a YAML writer.
$composeFile = Join-Path $instanceDir 'docker-compose.yml'
$doc | ConvertTo-Json -Depth 30 | Set-Content -Path $composeFile

docker compose -f $composeFile --project-directory $instanceDir up -d | Out-Host

# --- wait for the tier, then for the web client ---
$deadline = (Get-Date).AddMinutes(10)
do {
    Start-Sleep -Seconds 5
    $health = (docker inspect "bc-$Name" --format '{{.State.Health.Status}}' 2>$null)
} while ($health -notin @('healthy', 'unhealthy') -and (Get-Date) -lt $deadline)

$webPort = $cfg['BC_WEBCLIENT_HOST_PORT']
$web = '000'
if ($cfg['BC_WEBCLIENT'] -eq '1') {
    do {
        Start-Sleep -Seconds 5
        try {
            $web = "$((Invoke-WebRequest -Uri "https://localhost:$webPort/$Name/" -SkipCertificateCheck -SkipHttpErrorCheck -MaximumRedirection 0 -TimeoutSec 5 -ErrorAction SilentlyContinue).StatusCode)"
        } catch { $web = '000' }
    } while ($web -eq '000' -and (Get-Date) -lt $deadline)
}

$result = [ordered]@{
    instance   = $Name
    project    = $project
    health     = $health
    webClient  = "https://$($cfg['PUBLIC_HOST'])/$Name/"
    webStatus  = $web
    dev        = "http://localhost:$($cfg['BC_DEV_PORT'])/BC/dev"
    odata      = "http://localhost:$($cfg['BC_ODATA_PORT'])/BC/ODataV4"
    api        = "http://localhost:$($cfg['BC_API_PORT'])/BC/api/v2.0"
    manifest   = $manifest
}
if ($Json) { $result | ConvertTo-Json } else {
    $result.GetEnumerator() | ForEach-Object { '{0,-10} {1}' -f $_.Key, $_.Value }
}
if ($health -ne 'healthy') { exit 1 }
