#Requires -Version 7.0
<#
.SYNOPSIS
    Start the shared SQL Server that BC instances use.

.DESCRIPTION
    Creates the shared docker network and an "bc-mssql" compose project holding
    one SQL Server container. It is deliberately separate from any BC instance
    so it outlives them: stopping or deleting an instance never touches the
    databases.

    Unlike the single-repo BcOnLinux compose, data lives on a named volume
    rather than tmpfs. A shared server that wiped every instance's database on
    restart would be useless. Pass -Ephemeral for the tmpfs behaviour.

.EXAMPLE
    ./mssql-up.ps1 -SaPassword 'Passw0rd123!'
    ./mssql-up.ps1 -Json
#>
[CmdletBinding()]
param(
    # Only needed on first run; afterwards it is read back from the saved .env.
    [string]$SaPassword,
    [int]$Port = 11433,
    [string]$Image = 'ghcr.io/stefanmaron/msdyn365bc.on.linux/mssql:2022-zstd',
    [int]$MemoryLimitMb = 2048,
    [switch]$Ephemeral,
    [switch]$Json
)

$ErrorActionPreference = 'Stop'

$platformHome = if ($env:BC_PLATFORM_HOME) { $env:BC_PLATFORM_HOME } else { Join-Path $HOME '.bc-platform' }
$network      = 'bcnet'
$projectDir   = Join-Path $platformHome 'mssql'
$envFile      = Join-Path $projectDir '.env'

New-Item -ItemType Directory -Force -Path $projectDir | Out-Null

# Re-use the password from a previous run so the databases stay reachable.
if (-not $SaPassword -and (Test-Path $envFile)) {
    $existing = (Get-Content $envFile | Where-Object { $_ -like 'SA_PASSWORD=*' } | Select-Object -First 1)
    if ($existing) { $SaPassword = $existing.Substring('SA_PASSWORD='.Length) }
}
if (-not $SaPassword) {
    throw "No SA password. Pass -SaPassword on first run; later runs read it from $envFile."
}

if (-not (docker network ls --format '{{.Name}}' | Where-Object { $_ -eq $network })) {
    docker network create $network | Out-Null
    Write-Host "created network $network"
}

# The BC entrypoint imports a custom licence through OPENROWSET BULK, which
# reads the file from SQL Server's filesystem rather than the BC container's,
# so SQL needs the artifacts volume mounted too.
$dataMount = if ($Ephemeral) {
    "    tmpfs:`n      - /var/opt/mssql/data:size=4g,uid=10001,gid=10001"
} else {
    "    volumes:`n      - bc-mssql-data:/var/opt/mssql`n      - bc-artifacts:/bc/artifacts:ro"
}
$volumeDecl = if ($Ephemeral) { "  bc-artifacts:`n    name: bc-artifacts" } `
                         else { "  bc-mssql-data:`n    name: bc-mssql-data`n  bc-artifacts:`n    name: bc-artifacts" }

$compose = @"
# Generated by the mssql-up skill. Edit the skill, not this file.
name: bc-mssql
services:
  sql:
    image: `${BC_SQL_IMAGE}
    container_name: bc-mssql
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: `${SA_PASSWORD}
      MSSQL_MEMORY_LIMIT_MB: `${MSSQL_MEMORY_LIMIT_MB}
    ports:
      - "`${SQL_PORT}:1433"
$dataMount
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '`${SA_PASSWORD}' -C -No -Q "SELECT 1" || exit 1
      interval: 5s
      retries: 20
      start_period: 20s
    networks:
      - $network
volumes:
$volumeDecl
networks:
  ${network}:
    external: true
"@

Set-Content -Path (Join-Path $projectDir 'docker-compose.yml') -Value $compose -NoNewline:$false
@(
    "BC_SQL_IMAGE=$Image"
    "SA_PASSWORD=$SaPassword"
    "SQL_PORT=$Port"
    "MSSQL_MEMORY_LIMIT_MB=$MemoryLimitMb"
) | Set-Content -Path $envFile

docker compose --project-directory $projectDir up -d | Out-Host

# Wait for the healthcheck rather than reporting success on "container started".
$deadline = (Get-Date).AddMinutes(3)
do {
    Start-Sleep -Seconds 2
    $health = (docker inspect bc-mssql --format '{{.State.Health.Status}}' 2>$null)
} while ($health -ne 'healthy' -and (Get-Date) -lt $deadline)

$result = [ordered]@{
    project   = 'bc-mssql'
    container = 'bc-mssql'
    health    = $health
    host      = "localhost,$Port"
    network   = $network
    persistent = -not $Ephemeral.IsPresent
    composeFile = (Join-Path $projectDir 'docker-compose.yml')
}

if ($Json) { $result | ConvertTo-Json } else {
    $result.GetEnumerator() | ForEach-Object { '{0,-12} {1}' -f $_.Key, $_.Value }
}
if ($health -ne 'healthy') { exit 1 }
