#Requires -Version 7.0
<#
.SYNOPSIS
    Start the shared Traefik reverse proxy that fronts web apps on this machine.

.DESCRIPTION
    One proxy, one published port, many backends. Apps opt in with docker
    labels, so nothing here needs editing when an instance is added.

    It also carries the two pieces every BC instance needs:

      bc-transport@file  opens a second TLS connection to the backend and
                         validates it against the CA, so the app sees https
                         natively instead of inferring it from X-Forwarded-Proto.
      publichost@file    restores Host and Origin. A devtunnel relay rewrites
                         both to localhost:<port> whatever its flags say, which
                         breaks OAuth redirects and makes BC answer 403 to every
                         WebSocket upgrade.

    The dashboard is off unless -Dashboard is passed: it is unauthenticated.

.EXAMPLE
    ./traefik-up.ps1 -PublicHost 'example.euw.devtunnels.ms:8080' -CertDir ~/BcOnLinux/certs
    ./traefik-up.ps1 -Json
#>
[CmdletBinding()]
param(
    # Host:port the browser uses. Required on first run, remembered afterwards.
    [string]$PublicHost,
    # Directory holding ca.crt (and the leaf the backends serve).
    [string]$CertDir,
    [int]$Port = 8080,
    [string]$Image = 'traefik:v3.6',
    [switch]$Dashboard,
    [int]$DashboardPort = 8090,
    [switch]$Json
)

$ErrorActionPreference = 'Stop'

$platformHome = if ($env:BC_PLATFORM_HOME) { $env:BC_PLATFORM_HOME } else { Join-Path $HOME '.bc-platform' }
$network      = 'bcnet'
$projectDir   = Join-Path $platformHome 'traefik'
$envFile      = Join-Path $projectDir '.env'

New-Item -ItemType Directory -Force -Path $projectDir | Out-Null

function Get-Saved([string]$key) {
    if (-not (Test-Path $envFile)) { return $null }
    $line = Get-Content $envFile | Where-Object { $_ -like "$key=*" } | Select-Object -First 1
    if ($line) { $line.Substring($key.Length + 1) } else { $null }
}

if (-not $PublicHost) { $PublicHost = Get-Saved 'PUBLIC_HOST' }
if (-not $CertDir)    { $CertDir    = Get-Saved 'CERT_DIR' }
if (-not $PublicHost) { throw "No -PublicHost. Pass it on first run; later runs read it from $envFile." }
if (-not $CertDir)    { throw "No -CertDir. It must contain ca.crt used to validate backends." }

$CertDir = (Resolve-Path $CertDir).Path
if (-not (Test-Path (Join-Path $CertDir 'ca.crt'))) { throw "No ca.crt in $CertDir." }

if (-not (docker network ls --format '{{.Name}}' | Where-Object { $_ -eq $network })) {
    docker network create $network | Out-Null
    Write-Host "created network $network"
}

$dynamic = @"
# Generated by the traefik-up skill. Edit the skill, not this file.
http:
  serversTransports:
    bc-transport:
      # The compose service name, because the backend certificate carries
      # DNS:bc. That keeps this file free of per-instance names.
      serverName: bc
      rootCAs:
        - /certs/ca.crt
  middlewares:
    publichost:
      headers:
        customRequestHeaders:
          Host: "$PublicHost"
          Origin: "https://$PublicHost"
"@
Set-Content -Path (Join-Path $projectDir 'dynamic.yml') -Value $dynamic

$apiFlags = if ($Dashboard) {
    "      - --api.insecure=true`n      - --api.dashboard=true`n      - --entrypoints.traefik.address=:8090"
} else { '' }
$apiPorts = if ($Dashboard) { "      - `"`${DASHBOARD_PORT}:8090`"" } else { '' }

$compose = @"
# Generated by the traefik-up skill. Edit the skill, not this file.
name: bc-traefik
services:
  traefik:
    image: `${TRAEFIK_IMAGE}
    container_name: bc-traefik
    restart: unless-stopped
    ports:
      - "`${TRAEFIK_PORT}:8080"
$apiPorts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - `${CERT_DIR}:/certs:ro
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=$network
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --entrypoints.web.address=:8080
$apiFlags
      - --log.level=INFO
      - --accesslog
    networks:
      - $network
networks:
  ${network}:
    external: true
"@
Set-Content -Path (Join-Path $projectDir 'docker-compose.yml') -Value $compose

@(
    "TRAEFIK_IMAGE=$Image"
    "TRAEFIK_PORT=$Port"
    "DASHBOARD_PORT=$DashboardPort"
    "CERT_DIR=$CertDir"
    "PUBLIC_HOST=$PublicHost"
) | Set-Content -Path $envFile

docker compose --project-directory $projectDir up -d | Out-Host
Start-Sleep -Seconds 2
$state = (docker inspect bc-traefik --format '{{.State.Status}}' 2>$null)

$result = [ordered]@{
    project    = 'bc-traefik'
    state      = $state
    publicHost = $PublicHost
    entrypoint = "http://localhost:$Port"
    certDir    = $CertDir
    dashboard  = if ($Dashboard) { "http://localhost:$DashboardPort (unauthenticated)" } else { 'off' }
    network    = $network
}
if ($Json) { $result | ConvertTo-Json } else {
    $result.GetEnumerator() | ForEach-Object { '{0,-11} {1}' -f $_.Key, $_.Value }
}
if ($state -ne 'running') { exit 1 }
